### ISSUE TITLE
Downstream N14 - Timed items not highlighting despite being usable

### ISSUE THREAD

**Issue by BlueHNT** [Simple-Station/Einstein-Engines#705]
# Description

Once you reach the required time mark via `!type:CharacterJobRequirement` the item does not highlight itself in white and un-hide itself.

# Reproduction

1. Add item which needs `!type:CharacterJobRequirement`
2. Get required time
3. Item stays hidden despite requirements being fullfilled

# Expected behavior

1. Add item which needs `!type:CharacterJobRequirement`
2. Get required time
3. Item shows up normally, with the requirements being hidden as you fullfill them

# Media

```
- type: loadout
  id: LoadoutBoSMidwestT60
  category: Roles
  cost: 10
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladin
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidPaladin
      min: 72000 # 20 hours veterancy unlock
  items:
    - N14ClothingOuterPowerArmorT60
```

![image](https://github.com/user-attachments/assets/303bbd3f-13ce-48bb-835e-e6b239ca85f4)
![image](https://github.com/user-attachments/assets/5ad69f84-f51b-44fa-bd77-f6be63403c6f)

# Additional context

This was tested both on live server and in testing area and found to not be working properly
repo: _https://github.com/Vault-Overseers/nuclear-14_
tested suit locations: Resources/Prototypes/_Nuclear14/Loadouts/Roles/loadouts_bos_midwest.yml
